version: '3'

services:
  app:
    image: php:8.0-apache
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/html/app
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: mvc_db
      MYSQL_USER: root_user               # New user name
      MYSQL_PASSWORD: root_password       # New user password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
